name: Trigger auto deployment for my-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/my-container-app-AutoDeployTrigger-1ae90409-06da-474a-824d-f8c7fb64ced5.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: containerapptz.azurecr.io
          username: ${{ secrets.MYCONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.MYCONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: containerapptz.azurecr.io/my-container-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYCONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n my-container-app -g my-container-apps --server containerapptz.azurecr.io --username  ${{ secrets.MYCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.MYCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n my-container-app -g my-container-apps --image containerapptz.azurecr.io/my-container-app:${{ github.sha }}
